### ISSUE TITLE
`fromJust` exception on `listUnspent`

### ISSUE THREAD

**Issue by charlescharles** [cgaebel/network-bitcoin#18]
`listUnspent client Nothing Nothing (fromList ["mx6GFttCKxToALtb4rvjkc1GUuwNnY13Tc"])` causes fromJust to be called on Nothing somewhere. If I manually perform the request with `callApi` I get a value of type `FromJSON v => IO v`, and casting that to `IO (Vector UnspentTransaction)` causes the exception. I can't figure out why; I can't find any potential uses of fromJust in the source that might cause this. Any ideas?

**Comment by ericpashman** [comment]
What's the type of `fromList ["mx6GFttCKxToALtb4rvjkc1GUuwNnY13Tc"]`? The thing inside the list needs to be an `Address`, which is a synonym for a `HexString`, which is a synonym for `Text`. Possibly it is being treated as `String`, it gets mis-parsed into JSON, and there's a `fromJust` somewhere in the Aeson stack or in the other side of the API call.

Try adding an explicit type signature and see whether it works. (Sorry, not at my computer, so I can't try it.)

I'd suggest ripping all of the occurrences of `fromJust` (and other partial functions) out of the codebase regardless. "Obviously correct" usages have a curious way of turning out to be incorrect; if you use pattern matching instead we will at least get an incomplete patterns warning out of `-Wall`.

**Comment by charlescharles** [comment]
I had -XOverloadedStrings set, but you're right that it might be expecting a hex-encoded address. I tried this again, with `fromList ["6fb5cebbdde08fa61645e1a0841c31d97c8de20e959e99da9f" :: Address]` and I still get the fromJust exception. Here's the full command:

`listUnspent client Nothing Nothing $ (fromList ["6fb5cebbdde08fa61645e1a0841c31d97c8de20e959e99da9f"] :: Vector Address)`

I also made sure I'm using network-bitcoin-1.7.0, as previous versions have some potentially problematic usages of `fromJust`.

**Comment by ericpashman** [comment]
OK, turns out the bug is indeed in `network-bitcoin`, not farther down the Aeson stack; it's lurking in the only spot it could possibly have been lurking, in the call to `fromJust` in the definition of `getClient`, in `Network.Bitcoin.Internal`.

The bug occurs when you pass in an invalid URL; you need to include the "http://" prefix. If you're running  with default settings (i.e., on localhost, and if you substitute the appropriate username and password) it should work to define `client` in your example like this:

    let client = getClient "http://localhost:8332/" "username" "password"

To fix this, do we just want to throw an exception in `getClient` if the user provides an invalid URL? Personally, I dislike all these exceptions all over the place, but that's probably a separate discussion. ...

**Comment by cgaebel** [comment]
I'm ok with an exception + informative error message.

**Comment by charlescharles** [comment]
Thanks a ton! I'd been making calls successfully in the past and forgot about lazy eval/didn't even consider the `fromJust` in `getClient` as a potential cause. I have listUnspent working correctly now; I guess I'd been typing in the url incorrectly.

**Comment by ericpashman** [comment]
So you're OK for now, charlescharles? I'll submit a pull request that throws an informative exception when I get a few minutes, probably tomorrow. Have to run for now.

**Comment by charlescharles** [comment]
Yep, I've got it figured out; pretty simple mistake in hindsight. Appreciate your help!

**Comment by ericpashman** [comment]
My pull request just re-jiggers `getClient` a bit to expose the exception that `parseUrl` already throws if the user passes in an invalid URL.

The previous use of `fromJust` specialized the `MonadThrow m => ...` return type of `parseUrl` to `Maybe`, hiding the exception; my exception causes `parseUrl` to return in `IO`, re-exposing this exception:

    *** Exception: InvalidUrlException "localhost" "Invalid URL"

**Comment by charlescharles** [comment]
Closing since Eric's PR has been merged
